// Before adding a new tag, ensure it doesn't already exist in the array.
export const registryTags = [
  // Oui ui and ex tags
  "alert",
  "alert-ex-form",
  "autocomplete",
  "badge",
  "badge-ex",
  "base",
  "button",
  "button-group",
  "calendar",
  "card",
  "card-ex",
  "checkbox",
  "checkbox-group",
  "combo-box",
  "date-field",
  "date-picker",
  "dialog",
  "disclosure",
  "field",
  "field-error",
  "form",
  "grid-list",
  "group",
  "index",
  "input",
  "input-group",
  "keyboard",
  "label",
  "link",
  "list-box",
  "list-box-ex-pagination",
  "menu",
  "modal",
  "modal-ex-sheet",
  "number-field",
  "popover",
  "radio-group",
  "search-field",
  "select",
  "separator",
  "sidebar",
  "sidebar-ex",
  "slider",
  "switch",
  "table",
  "tabs",
  "text-area",
  "text-field",
  "toggle-button",
  "toggle-button-group",
  "tooltip",
  "tree",

  // Generic tags
  "avatar",
  "disabled",
  "error-boundary",
  "icon",
  "invalid",
  "login",
  "multiple",
  "provider",
  "react-router",
  "sheet",
  "theme",
] as const;

export type RegistryTag = (typeof registryTags)[number];
